Feat/53 questions form
hngprojects/hng_boilerplate_remix pull request #123
Opened 2024-07-19 17:11 UTC by abdulmalikyusuf

Developed an additional questions form where users can submit specific inquiries or questions that are not addressed in the FAQs section. The form includes fields for user's name, email address, phone number, and inquiry. Also implemented form validation.

2024-07-20 17:39 UTC, chumex412 commented
Resolve the conflicts

2024-07-20 20:51 UTC, SirhmVFX requested changes

2024-07-20 20:51 UTC, SirhmVFX commented on app/components/faq/form.tsx
Use global colors, don't hardcode the colors

2024-07-20 23:07 UTC, abdulmalikyusuf commented on app/components/faq/form.tsx
Okay, will change that

2024-07-20 23:23 UTC, abdulmalikyusuf commented on app/components/faq/form.tsx
Please can you add this variable to the globals css file: --primary: 25 95% 53% //hsl value. I need it as the primary color'

2024-07-21 09:01 UTC, oreoluwa212 commented
I dont see your tests screenshots

2024-07-21 09:02 UTC, oreoluwa212 requested changes
Add a video too of your components working after you pulled from dev

2024-07-21 09:29 UTC, abdulmalikyusuf commented
> I dont see your tests screenshots

From the task posted on slack, only the next.js repo was to be tested and the packages for testing (vitest and others) are not included in the repository

2024-07-21 10:01 UTC, closed without merging