feat: implement search function for Faq
hngprojects/hng_boilerplate_remix pull request #183
Opened 2024-07-20 02:28 UTC by favourachara07

### What Changes I made
## What I was told to do
Implement the search functionality for the FAQ component using keywords
## What I did
I made changes to the root file(index.tsx)
I added the assets folder that contained the svg and logo
The component and search functionality 
### Screenshots
![Screenshot (43)](https://github.com/user-attachments/assets/17ca3ed2-5df8-4254-92db-ff19c111d18a)

2024-07-20 17:45 UTC, chumex412 commented
Resolve the conflicts

2024-07-20 17:53 UTC, chumex412 requested changes

2024-07-20 17:53 UTC, chumex412 commented on app/routes/_index.tsx
> +                  className="text-black hover:text-white border border-orange-600 hover:bg-orange-600 focus:ring-4 focus:outline-none focus:ring-orange-300 font-medium rounded-md text-sm px-5 py-2.5
Why are you implementing your own nav bar?

2024-07-20 17:53 UTC, chumex412 commented on app/routes/_index.tsx
> +      <main>
is this the proper route for the FAQ? Please use the proper route.

2024-07-20 17:53 UTC, chumex412 commented on app/routes/_index.tsx
> +                    BoilerPlate
Why are you creating the footer yourself, please look for the footer and nav bar components and use those instead

2024-07-21 19:10 UTC, favourachara07 commented
> Resolve the conflicts

I have resolved them
Please your review

2024-07-21 20:26 UTC, shalomtaiwo submitted a review, later dismissed
Please resolve conflict

2024-07-21 22:05 UTC, SirhmVFX approved these changes

2024-07-22 10:22 UTC, SirhmVFX commented
your branch has conflicts... resolve them

2024-07-23 18:57 UTC, chumex412 approved these changes

2024-07-23 18:59 UTC, chumex412 approved these changes

2024-07-23 19:00 UTC, chumex412 approved these changes

2024-07-23 19:00 UTC, merged