Feat/116 user dashboard password settings page
hngprojects/hng_boilerplate_remix pull request #243
Opened 2024-07-20 22:43 UTC by Lftobs

# Description

**Closes [#116](https://github.com/hngprojects/hng_boilerplate_remix/issues/116)

# Changes proposed

 Added dashboard password setting page

## What were you told to do?

User Dashboard Password Settings Page

## What did you do?
-  Develop the Password Settings page based on the provided design and requirements.
-  Implement a responsive layout that works well across different devices and browsers.
-  Create password input fields with mask/unmask functionality.
-  Implement client-side validation for password requirements.
-  Develop server-side logic for password update.
-  Implement error handling and success messages.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

![Screenshot from 2024-07-20 17-32-47-1](https://github.com/user-attachments/assets/d6be0451-ebd4-4934-bf78-712557ec0951)

![Screenshot from 2024-07-20 17-37-29](https://github.com/user-attachments/assets/79fda990-b177-44a7-846f-02824afbf526)

2024-07-20 22:55 UTC, SirhmVFX requested changes

2024-07-20 22:55 UTC, SirhmVFX commented on .vscode/settings.json
not allowed to edit settings.json

2024-07-20 22:55 UTC, SirhmVFX commented on app/routes/dashboard.password-settings/route.tsx
No side bar component

2024-07-20 23:05 UTC, Lftobs commented on app/routes/dashboard.password-settings/route.tsx
its a component in issue [#5](https://github.com/hngprojects/hng_boilerplate_remix/issues/5#issue-2415567568l) and [#146](https://github.com/hngprojects/hng_boilerplate_remix/issues/148#issue-2419537228)

2024-07-20 23:08 UTC, Lftobs commented on .vscode/settings.json
fixed

2024-07-21 00:19 UTC, SirhmVFX approved these changes

2024-07-21 00:19 UTC, merged