feat: HNG-58-super-admin-products-list-page
hngprojects/hng_boilerplate_remix pull request #286
Opened 2024-07-21 16:15 UTC by jerahmeel200

# Description

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-21 19:11 UTC, chumex412 requested changes

2024-07-21 19:11 UTC, chumex412 commented on app/components/ui/revenueCard/cardComponent.tsx
> +import React from "react";
Please only import what you need from React, remove 

All instances of

import React from "react"

If you need HTMLAttributes import it alone as

import { HTMLAttributes, FC } from "react"

2024-07-22 17:10 UTC, jerahmeel200 commented
i have made the requested changes please merge thanks

2024-07-22 18:28 UTC, mrcoded requested changes
fill this on your PR Changes proposed
What were you told to do?
What did you do?

2024-07-22 18:53 UTC, mrcoded approved these changes

2024-07-22 18:54 UTC, merged