Feat/hng 16 implement login page
hngprojects/hng_boilerplate_remix pull request #329
Opened 2024-07-21 22:56 UTC by seshto13

# Description

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-21 23:21 UTC, shalomtaiwo requested changes

2024-07-21 23:21 UTC, shalomtaiwo commented on .gitignore
Please don't add the lock files into gitignore. Fix it

2024-07-21 23:40 UTC, seshto13 commented on .gitignore
Ok will fix that now

2024-07-21 23:52 UTC, mrcoded commented
Please edit your PRs to contain why you are making the PR @seshto13

2024-07-21 23:58 UTC, seshto13 commented
> Please edit your PRs to contain why you are making the PR @seshto13

I have edited my PR . kindly check

2024-07-22 00:01 UTC, seshto13 commented on .gitignore
I have fixed the issued

2024-07-22 06:09 UTC, shalomtaiwo approved these changes

2024-07-22 06:09 UTC, merged